/**
 * Common HTML Template Helpers
 * Reusable functions for generating HTML components across different problem solvers
 */

/**
 * Generate common header for all problem types
 * @param {string} lang - Language code ('en' or 'bn')
 * @param {Object} problem - Problem object
 * @returns {string} - HTML for common header
 */
export function getCommonHeader(lang, problem) {
    const isEnglish = lang === 'en';
    const title = isEnglish 
        ? (problem.problemType?.title?.en || 'Math Problem Solution')
        : (problem.problemType?.title?.bn || 'গণিত সমস্যা সমাধান');
    const subtitle = isEnglish
        ? (problem.description?.en || 'Step-by-step solution')
        : (problem.description?.bn || 'ধাপে ধাপে সমাধান');
    const brandName = isEnglish ? 'MLP Solver' : 'MLP সলভার';
    
    return `
    <header class="bg-white border-bottom mb-4">
        <nav class="navbar navbar-expand-lg navbar-light bg-white">
            <div class="container">
                <a class="navbar-brand fw-bold fs-4" href="#">${brandName}</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
        <div class="bg-white py-5 text-center">
            <div class="container">
                <h1 class="display-5 fw-semibold mb-2">${title}</h1>
                <p class="text-muted mb-0">${subtitle}</p>
            </div>
        </div>
    </header>`;
}

/**
 * Generate common footer for all problem types
 * @param {string} lang - Language code ('en' or 'bn')
 * @returns {string} - HTML for common footer
 */
export function getCommonFooter(lang) {
    const isEnglish = lang === 'en';
    const generatedText = isEnglish 
        ? `Generated by MLP Solver • ${new Date().toLocaleDateString('en-US')}`
        : `MLP সলভার দ্বারা তৈরি • ${new Date().toLocaleDateString('bn-BD')}`;
    
    return `
    <footer class="bg-white border-top mt-auto py-4">
        <div class="container">
            <p class="text-muted text-center small mb-0">${generatedText}</p>
        </div>
    </footer>`;
}

/**
 * Get common CSS styles for HTML templates
 * @returns {string} - CSS styles (minimal, using Bootstrap defaults)
 */
export function getCommonStyles() {
    return `
        /* Minimal custom styles - Bootstrap handles the rest */
        body {
            min-height: 100vh;
            display: flex;
            flex-direction: column;
        }
        
        .main-content {
            flex: 1;
        }
        
        .step-number {
            width: 36px;
            height: 36px;
            display: flex;
            align-items: center;
            justify-content: center;
            flex-shrink: 0;
        }
        
        @media print {
            .navbar {
                display: none;
            }
        }
    `;
}

/**
 * Generate complete HTML document structure
 * @param {string} lang - Language code ('en' or 'bn')
 * @param {Object} problem - Problem object
 * @param {string} bodyContent - Main body content HTML
 * @returns {string} - Complete HTML document
 */
export function generateCompleteHTML(lang, problem, bodyContent) {
    const isEnglish = lang === 'en';
    
    if (isEnglish) {
        return `
<body>
    ${getCommonHeader(lang, problem)}
    ${bodyContent}
    ${getCommonFooter(lang)}
</body>`;
    } else {
        return `
<div>
    ${getCommonHeader(lang, problem)}
    ${bodyContent}
    ${getCommonFooter(lang)}
</div>`;
    }
}
